Name:           tel_script
Version:        0.201510
Release:        1%{?dist}
Summary:        App::Tel Perl module
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/App-Tel/
Source0:        http://www.cpan.org/modules/by-module/App/App-Tel-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 0:5.10.0
BuildRequires:  perl(Expect) >= 0.0
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(File::KeePass)
BuildRequires:  perl(Hash::Merge::Simple) >= 0.0
BuildRequires:  perl(IO::Stty) >= 0.0
BuildRequires:  perl(Passwd::Keyring::Auto)
BuildRequires:  perl(Term::ANSIColor)
BuildRequires:  perl(Term::ReadKey)
BuildRequires:  perl(Test::Most) >= 0.31
Requires:       perl(Expect) >= 0.0
Requires:       perl(File::KeePass)
Requires:       perl(Hash::Merge::Simple) >= 0.0
Requires:       perl(IO::Stty) >= 0.0
Requires:       perl(Passwd::Keyring::Auto)
Requires:       perl(Term::ANSIColor)
Requires:       perl(Term::ReadKey)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
tel provides the following:
* Use a simple, single command to connect to multiple network device types.
* Create aliases for hard to type router names or commands.
* Handles terminal-related issues, such as proper backspace.
* clogin-style CLI arguments (via -c and -x).
* Color highlighting.
* Optional global config that supports multiple users.
* Keepass and Keyring support
* Handles automatic logins for text-based user interfaces common on older
  networking devices.
* Highly customizable

%prep
%setup -q -n App-Tel-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc COMMANDS.md dottelrc.sample README.md
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Sun Dec 28 2014 rdrake@cpan.org 0.201002-1
- Specfile autogenerated by cpanspec 1.78.
