#!/usr/bin/env perl

eval 'exec perl  -S $0 ${1+"$@"}'
    if 0; # not running under some shell

use strict;
use warnings;

# unexpected EOF during login() method needs to happen before the Password is
# sent.. :(
exit;


