# see https://metacpan.org/pod/Devel::Cover::Report::Coveralls for a good
# example workflow.

on:
  push:
    branches:
      - "master"
<<<<<<< Updated upstream
      - "github-ci-testing"
=======
      - "v1.0.0-testing"
>>>>>>> Stashed changes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.34'
          install-modules-with: cpanm
          install-modules-args: --with-develop --with-configure --with-all-features
      - run: perl -V
      - run: perl Makefile.PL
      - run: prove -l t
      - name: Run tests with coverage
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: cover -test -ignore local/ -report Coveralls

