# see https://metacpan.org/pod/Devel::Cover::Report::Coveralls for a good
# example workflow.

on:
  push:
    branches:
      - "master"
      - "v1.0.0-testing"
      - "github-ci-testing"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.34'
          install-modules-with: cpanm
          install-modules-args: --with-develop --with-configure --with-all-features
      - run: perl -V
      - run: perl Makefile.PL
      - run: prove -l t
      - name: Run tests with coverage
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: cover -test -ignore local/ -report Coveralls

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3.6.0
        with:
          platforms: arm64

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/rfdrake/tftpd-hpa:latest
